---
title: "SvX Boost 1x D30 and D90 Lesion Area"
author: "Pablo Maldonado"
date: "11/2/2023"
output: html_document
---


```{r global options, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, error = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(readxl)
library(dplyr)
library(purrr)
library(tidyr)
library(stringr)
library(tidyverse)
library(gridExtra)
library(ggplot2)
library(ggpubr)
library(scales)
library(gridExtra)
library(emmeans)
library(viridis)
library(vcd)
library(ggmosaic)
library(kableExtra)
```

```{r}

# Define the file path
file_path <- "/Volumes/rstor-henao_lab/SolaVAX-TB/GitHub/SolaVAX-TB/Lesion_analysis/SolaVAX-TB_Lesion-area-cell-counts.xlsx"

# Read the Excel file into a data frame
lesion_area <- read_excel(file_path)

lesion_area

split <- str_split_fixed(lesion_area$Name, "\\.", 4)
colnames(split) <- c("name", "mouse", "section", "data")
split <- as.data.frame(split)
split$day <- str_extract(split$name, "\\d{2}$")
split$name <- str_remove(split$name, "\\d{2}$")

lesion_area_expanded <- cbind(split, lesion_area)
lesion_area_expanded <- lesion_area_expanded %>%
  select(-"Name", -"Perimeter µm", -"Area µm^2")


lesion_area_expanded <- lesion_area_expanded %>%
  pivot_wider(names_from = data, values_from = Detections) %>%
  mutate(percent_area = (density/cells)*100)


percent_area <- lesion_area_expanded %>%
  group_by(name, mouse, day) %>%
  summarise(average_percent_burden = mean(percent_area), .groups = "drop")

percent_area  <- percent_area %>%
  filter(!(name == "Saline" & mouse == 2 & day == 30)) %>%
  filter(!(name == "INInulin" & mouse == 1 & day == 90))
percent_area 

# # Recode the condition and group names
percent_area  <- percent_area  %>%
  mutate(name = ifelse(name == "IMCPG", "BCG+SvX-IM-CpG",
                       ifelse(name == "INInulin", "BCG+SvX-IN-Inulin", name)))
percent_area$name <- factor(percent_area$name, levels = c("Saline", "BCG1x", "BCG2x", "BCG+SvX-IN-Inulin", "BCG+SvX-IM-CpG"))
```

this works for one timepoint or sex at a time 

```{r}
# # ANOVA
# anova_result <- aov(average_percent_burden ~ name, data = percent_area)
# 
# # Extract p-values from ANOVA
# p_values <- summary(anova_result)[["Pr(>F)"]]
# 
# # Perform Tukey's post hoc test for group comparisons
# tukey_result <- TukeyHSD(anova_result)
# 
# # Extract p-values from Tukey's test
# p_values <- tukey_result[[1]][, "p adj"]
# 
# p_values
# # Specify the pairs of groups for significance bars
# significant_comparisons <- p_values < 0.05  # Example: using a significance level of 0.05
# significant_comparisons
# 
# # Create a data frame
# comparison_df <- data.frame(
#   p_value = p_values,
#   significant = significant_comparisons)
# comparison_df <- comparison_df %>% rownames_to_column("vaccine")
# 
# comparison_df
# 
# 
# # Create a function to add asterisks based on p-values
# add_asterisks <- function(p_value) {
#   if (p_value < 0.00009) {
#     return("****")
#   } else if (p_value < 0.0009) {
#     return("***")
#   } else if (p_value < 0.009) {
#     return("**")
#   } else if (p_value < 0.05) {
#     return("*")
#   } else {
#     return("ns")
#   }
# }
# 
# # Add asterisks to the comparison_df
# comparison_df$`significance level` <- sapply(comparison_df$p_value, add_asterisks)
# 
# # Display the updated comparison_df
# print(comparison_df)
# 
# kable(comparison_df, caption = "Comparison Results", align = "c")
```


```{r}

day30_df <- percent_area %>%
  filter(day == "30")

day90_df <- percent_area %>%
  filter(day == "90")

# DAY 30 ANOVA
day30_anova_result <- aov(average_percent_burden ~ name, data = day30_df)

# Extract p-values from ANOVA
day30_p_values <- summary(day30_anova_result)[["Pr(>F)"]]

# Perform Tukey's post hoc test for group comparisons
day30_tukey_result <- TukeyHSD(day30_anova_result)

# Extract p-values from Tukey's test
day30_p_values <- day30_tukey_result[[1]][, "p adj"]

day30_p_values
# Specify the pairs of groups for significance bars
day30_significant_comparisons <- day30_p_values < 0.05  # Example: using a significance level of 0.05
day30_significant_comparisons

# DAY 90 ANOVA
day90_anova_result <- aov(average_percent_burden ~ name, data = day90_df)

# Extract p-values from ANOVA
day90_p_values <- summary(day90_anova_result)[["Pr(>F)"]]

# Perform Tukey's post hoc test for group comparisons
day90_tukey_result <- TukeyHSD(day90_anova_result)

# Extract p-values from Tukey's test
day90_p_values <- day90_tukey_result[[1]][, "p adj"]

# Specify the pairs of groups for significance bars
day90_significant_comparisons <- day90_p_values < 0.05  # Example: using a significance level of 0.05
day90_significant_comparisons


```


```{r}
day30_combined_df <- as.data.frame(day30_p_values) %>%
  rownames_to_column("group") %>%
  left_join(as.data.frame(day30_significant_comparisons) %>%
              rownames_to_column("group"), by = "group")
day30_combined_df

day90_combined_df <- as.data.frame(day90_p_values) %>%
  rownames_to_column("group") %>%
  left_join(as.data.frame(day90_significant_comparisons) %>%
              rownames_to_column("group"), by = "group")
day90_combined_df

joined_significnce <- left_join(day30_combined_df, day90_combined_df, by = "group")


joined_significnce
```

```{r}

BCG1x30result <- with(day30_df, t.test(average_percent_burden[name == "Saline"], average_percent_burden[name == "BCG1x"]))

BCG1x30resultp_value <- BCG1x30result$p.value
BCG1x30resultp_value 

with(day30_df, t.test(average_percent_burden[name == "Saline"], average_percent_burden[name == "BCG2x"]))
with(day30_df, t.test(average_percent_burden[name == "Saline"], average_percent_burden[name == "BCG+SvX-IN-Inulin"]))
with(day30_df, t.test(average_percent_burden[name == "Saline"], average_percent_burden[name == "BCG+SvX-IM-CpG"]))

with(day90_df, t.test(average_percent_burden[name == "Saline"], average_percent_burden[name == "BCG1x"]))
with(day90_df, t.test(average_percent_burden[name == "Saline"], average_percent_burden[name == "BCG2x"]))
with(day90_df, t.test(average_percent_burden[name == "Saline"], average_percent_burden[name == "BCG+SvX-IN-Inulin"]))
with(day90_df, t.test(average_percent_burden[name == "Saline"], average_percent_burden[name == "BCG+SvX-IM-CpG"]))



```


```{r}
ggplot(data = percent_area, aes(x = day, y = average_percent_burden, fill = name, color = name)) +
  geom_boxplot(width = 0.5, alpha = 0.7, position = position_dodge(width = 0.75)) +
  geom_point(size = 3, shape = 21, alpha = 0.9, na.rm = TRUE, color = "black",
             position = position_dodge(width = 0.75)) +
  scale_color_viridis_d(name = " ", alpha = 1) +  
  scale_fill_viridis_d(name = " ", alpha = 1) +  
  #facet_wrap(~ day, scales = "free_y") +
  labs(title = " ", x = " ", y = "Percent Lesion Burden", color = "Vaccine") +
  theme_bw() + 
  theme(
    strip.text = element_text(color = "black", size = 1.3 * rel(1)),
    #axis.text.x = element_blank(),
    axis.text.x = element_text(color = "black", size = 1.3 * rel(1)),
    axis.title.x = element_text(color = "black", size = 1.3 * rel(1)),
    axis.text.y = element_text(color = "black", size = 1.3 * rel(1)),
    axis.title.y = element_text(color = "black", size = 1.4 * rel(1)),
    legend.position = "bottom",
    legend.title = element_text(color = "black", size = 1.3 * rel(1)),
    legend.text = element_text(color = "black", size = .9 * rel(1)),
    plot.title = element_text(color = "black", size = 15)) +
scale_y_continuous(labels = scales::percent_format(scale = 1), name = "Percent Lesion Burden", 
                     limits = c(0, 50))
```

